run:
  concurrency: 4
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - test/utils/k8simported
  modules-download-mode: vendor
linters:
  disable-all: true
  enable:
    - errcheck
    - bodyclose
    - exportloopref
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - depguard
linters-settings:
  misspell:
    locale: US
    ignore-words:
      - NRO
      - nro
      - numaresource
      - numa
      - NUMA
  depguard:
    rules:
      main:
        list-mode: original
        files:
          - $all
          - "!$test"
        deny:
          - pkg: "k8s.io/kubernetes"
            desc: Importing k8s.io/kubernetes as library is not supported
      test:
        list-mode: lax
        files:
          - $test
        deny:
          - pkg: "k8s.io/kubernetes"
            desc: Importing k8s.io/kubernetes as library is not supported
