apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sampledevices-rb
  namespace: sampledevices
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sampledevices-ro
subjects:
- kind: ServiceAccount
  name: sampledevices-sa
  namespace: sampledevices
