apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: idle-gu-job-sched-stall
    job-name: generic-pause
  name: generic-pause
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 4
  manualSelector: false
  parallelism: 4
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    metadata:
      labels:
        app: idle-gu-job-sched-stall
        job-name: generic-pause
    spec:
      containers:
      - args:
        - 1s
        command:
        - /bin/sleep
        image: quay.io/openshift-kni/pause:test-ci
        imagePullPolicy: IfNotPresent
        name: generic-job-idle
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: idle-gu-job-sched-stall
        matchLabelKeys:
        - pod-template-hash
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
