apiVersion: v1
kind: Pod
metadata:
  generateName: chk-pod-
spec:
  schedulerName: topo-aware-scheduler
  containers:
  - name: ctrreschk
    image: quay.io/fromani/ctrreschk:v0.0.3
    imagePullPolicy: Always
    command: ["/usr/local/bin/ctrreschk", "-S", "align"]
    resources:
      limits:
        cpu: 1
        memory: 256Mi
      requests:
        cpu: 1
        memory: 256Mi
