apiVersion: v1
kind: Pod
metadata:
  name: testpod1
spec:
  schedulerName: topo-aware-scheduler
  containers:
  - name: testcnt1
    command: ["/usr/local/bin/ctrreschk", "-S", "align"]
    image: quay.io/fromani/ctrreschk:v0.0.3
    resources:
      limits:
        cpu: '32'
        memory: 1000Mi
        example.com/deviceA: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod2
spec:
  schedulerName: topo-aware-scheduler
  containers:
  - name: testcnt2
    command: ["/usr/local/bin/ctrreschk", "-S", "align"]
    image: quay.io/fromani/ctrreschk:v0.0.3
    resources:
      limits:
        cpu: '32'
        memory: 1000Mi
        example.com/deviceA: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod3
spec:
  schedulerName: topo-aware-scheduler
  containers:
  - name: testcnt3
    command: ["/usr/local/bin/ctrreschk", "-S", "align"]
    image: quay.io/fromani/ctrreschk:v0.0.3
    resources:
      limits:
        cpu: '32'
        memory: 1000Mi
        example.com/deviceA: 1
