name: CI E2E - for tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  e2e-tools:
    runs-on: ubuntu-20.04
    env:
      LOG_DIR: /tmp/test_e2e_logs
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1

    - name: Verify modules
      run: go mod verify

    - name: Build tools test binary
      run: |
        make binary-e2e-tools

    - name: Build tools
      run: |
        make build-tools binary-nrocli

    - name: Create K8s Kind Cluster
      run: |
        # kind is part of 20.04 image, see: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
        kind version
        kind create cluster --config=hack/kind-config-e2e-no-registry.yaml --image kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
        kubectl label node kind-worker node-role.kubernetes.io/worker=''

    - name: Deploy RTE Operator
      run: |
        # we only need the manifests, this happens to be the easiest way known to date
        KUSTOMIZE_DEPLOY_DIR="config/kind-ci/" make deploy

    - name: E2E Tests
      run: |
        export KUBECONFIG=${HOME}/.kube/config
        hack/run-test-tools-e2e.sh --no-color

    - name: Export E2E Tests logs
      if: ${{ failure() }}
      run: |
        mkdir -p ${LOG_DIR}
        for pod in $(kubectl get pods -n $E2E_NAMESPACE_NAME --no-headers=true -o custom-columns=NAME:.metadata.name)
        do
          oc logs $pod -n $E2E_NAMESPACE_NAME --all-containers=true > ${LOG_DIR}/${pod}.log
          oc describe pod $pod -n $E2E_NAMESPACE_NAME > ${LOG_DIR}/${pod}.describe.log
        done

    - name: Archive E2E Tests logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: test_e2e_logs
        path: ${LOG_DIR}/

    - name: Export kind logs
      if: ${{ failure() }}
      run: |
        kind export logs /tmp/kind_logs

    - name: Archive kind logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: kind_logs
        path: /tmp/kind_logs
